name: 'PivotTech GradingAction'
description: 'An automated solution for reporting student achievement'
inputs:
  adminEndpointURL:
    description: "What endpoint to submit grades to"
    required: true
  coverageReportPath:
    description: "A relative path to where to locate test coverage reports"
    required: true
    default: ''
outputs:
  grade:
    description: "The resulting grade from applying the grading action"
runs:
  using: 'node12'
  main: './dist/index.js'
      
  